import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="relative flex flex-1 grainy-light  mx-auto mt-[68px]  min-h-[calc(100vh-136px)]">
          <Provider>{children}</Provider>
        </div>
        <section className="relative">
          <Footer />
        </section>
      </body>
    </html>
  );
}
